name: Daily Log Commit


permissions:
  contents: write   # 👈 Add this line!!



on:
  schedule:
    - cron: "0 12 * * *" # runs every day at noon UTC
  workflow_dispatch: # allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ensure daily log file exists
        run: |
          touch daily-log.md

      - name: Update daily log
        run: |
          echo "Last update: $(date)" >> daily-log.md

      - name: Commit changes
        run: |
          git config --global user.name 'umammahh'
          git config --global user.email 'umamaqasim420@gmail.com'
          git add daily-log.md
          git commit -m "chore: daily log update" || echo "No changes to commit"
          git push

